#!/bin/bash
# Cloudflare Pages Setup Helper
# Run this after code is on GitHub

echo "=========================================="
echo "Cloudflare Pages Setup Steps"
echo "=========================================="
echo ""
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Sign in (or create free account)"
echo "3. Click 'Pages' in left sidebar"
echo "4. Click 'Create a project'"
echo "5. Click 'Connect to Git'"
echo "6. Authorize GitHub if prompted"
echo "7. Select repository: pipeln/wilkesboro-today"
echo ""
echo "Build Configuration:"
echo "  - Project name: wilkesboro-today"
echo "  - Production branch: main"
echo "  - Build command: npm run build"
echo "  - Build output directory: dist"
echo ""
echo "8. Click 'Save and Deploy'"
echo ""
echo "=========================================="
echo "After first deploy, add Environment Variable:"
echo "=========================================="
echo "Go to: Project Settings → Environment variables"
echo "Add: AITABLE_TOKEN = uskNPM9fPVHOgAGbDepyKER"
echo ""
echo "=========================================="
echo "Add GitHub Secrets for Auto-Deploy:"
echo "=========================================="
echo "Go to: https://github.com/pipeln/wilkesboro-today/settings/secrets/actions"
echo "Add these secrets:"
echo "  - CLOUDFLARE_API_TOKEN (get from Cloudflare dashboard)"
echo "  - CLOUDFLARE_ACCOUNT_ID (shown in Cloudflare sidebar)"
echo "  - AITABLE_TOKEN = uskNPM9fPVHOgAGbDepyKER"
echo ""
echo "Your site will be live at:"
echo "  https://wilkesboro-today.pages.dev"
echo "=========================================="
